import type { TravelRoute, RouteRegionFilterItem, RouteRegion } from "./routesTypes";

export const ROUTE_REGION_FILTERS: readonly RouteRegionFilterItem[] = [
  { key: "semua", label: "Semua Rute" },
  { key: "bandung-utara", label: "Bandung Utara" },
  { key: "bandung-selatan", label: "Bandung Selatan" },
  { key: "rute-khusus", label: "Rute Khusus" },
] as const;

export const TRAVEL_ROUTES: readonly TravelRoute[] = [
  {
    id: "RT-01",
    order: 1,
    slug: "sukawana-cikole",
    name: "Sukawana–Cikole",
    region: "bandung-utara",
    regionLabel: "Bandung Utara",
    area: "Lembang",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Petualangan Sukawana–Cikole yang Menantang",
    shortDescription: "Perjalanan dari kawasan kebun teh Sukawana menuju hutan pinus Cikole melalui jalur batu, tanah merah, cerukan, dan lumpur.",
    longDescription: "Rute Sukawana–Cikole memadukan lanskap perkebunan teh dan suasana hutan pinus dalam perjalanan Land Rover klasik. Karakter lintasan dapat berubah mengikuti hujan, kondisi jalur, dan hasil pemeriksaan WNB sebelum keberangkatan.",
    duration: {
      dry: "3–4 jam",
      rainy: "5–6 jam",
      note: "Estimasi bersifat indikatif dan dapat berubah mengikuti kondisi perjalanan.",
    },
    landscape: "Kebun teh dan hutan pinus",
    trackCharacteristics: [
      "Jalur batu atau makadam",
      "Tanah merah",
      "Cerukan dan genangan",
      "Lintasan hutan",
    ],
    attractions: [
      "Lanskap perkebunan teh Sukawana",
      "Suasana hutan pinus Cikole",
      "Pengalaman perjalanan menggunakan Land Rover klasik",
    ],
    activities: [
      "Jelajah off-road",
      "Menikmati lanskap",
      "Dokumentasi pada titik aman yang ditentukan kru",
    ],
    seasonNote: "Hujan dapat membuat lintasan lebih licin dan berlumpur serta menambah waktu perjalanan.",
    meetingPoint: "Fleksibel di Bandung, Lembang, Cikole, atau Sukawana berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Sukawana secara umum",
    finishArea: "Kawasan Cikole secara umum",
    publicSafetyNotes: [
      "Kondisi Rute diperiksa kembali sebelum perjalanan.",
      "Peserta wajib mengikuti arahan driver dan helper.",
      "Rute dapat disesuaikan atau dialihkan apabila kondisi tidak memungkinkan.",
    ],
    media: {
      alt: "Visual perjalanan Land Rover klasik di Rute Sukawana–Cikole",
    },
  },
  {
    id: "RT-02",
    order: 2,
    slug: "cikole-sukawana-jalur-balik",
    name: "Cikole–Sukawana (Jalur Balik)",
    region: "bandung-utara",
    regionLabel: "Bandung Utara",
    area: "Lembang",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Tantangan Tanjakan Cikole–Sukawana",
    shortDescription: "Perjalanan arah balik dari Cikole menuju Sukawana dengan karakter tanjakan berbatu, tanah, dan lintasan hutan yang lebih menantang.",
    longDescription: "Arah perjalanan Cikole–Sukawana memiliki pengalaman berbeda dari RT-01 karena beberapa bagian lintasan berubah menjadi tanjakan. Pemilihan Rute dilakukan melalui konfirmasi WNB dengan mempertimbangkan cuaca, kondisi jalur, dan kesiapan perjalanan.",
    duration: {
      dry: "3,5–4,5 jam",
      rainy: "5–6 jam",
      note: "Estimasi bersifat indikatif dan dapat berubah mengikuti kondisi perjalanan.",
    },
    landscape: "Hutan dan jalur tanjakan kawasan Lembang",
    trackCharacteristics: [
      "Tanjakan berbatu",
      "Jalur tanah",
      "Lintasan hutan",
      "Perubahan traksi setelah hujan",
    ],
    attractions: [
      "Suasana hutan Bandung Utara",
      "Pengalaman tanjakan dengan Land Rover klasik",
      "Karakter perjalanan arah balik yang berbeda",
    ],
    activities: [
      "Jelajah off-road",
      "Menikmati suasana hutan",
      "Dokumentasi pada titik aman",
    ],
    seasonNote: "Setelah hujan, permukaan dapat menjadi lebih licin sehingga waktu dan susunan perjalanan dapat berubah.",
    meetingPoint: "Fleksibel di Bandung, Lembang, atau Cikole berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Cikole secara umum",
    finishArea: "Kawasan Sukawana secara umum",
    publicSafetyNotes: [
      "Penggunaan Rute dikonfirmasi setelah pemeriksaan kondisi jalur.",
      "Peserta wajib mengikuti posisi duduk dan arahan keselamatan kru.",
      "Rute dapat dialihkan apabila cuaca atau lintasan tidak memungkinkan.",
    ],
    media: {
      alt: "Visual Land Rover klasik menanjak pada Rute Cikole–Sukawana",
    },
  },
  {
    id: "RT-03",
    order: 3,
    slug: "sukawana-puncak-upas",
    name: "Sukawana–Puncak Upas",
    region: "bandung-utara",
    regionLabel: "Bandung Utara",
    area: "Tangkuban Parahu",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Ekspedisi Sukawana–Puncak Upas",
    shortDescription: "Perjalanan pegunungan dari Sukawana menuju kawasan Puncak Upas dengan suasana hutan, bebatuan, akar, kabut, dan karakter ekspedisi.",
    longDescription: "Rute Sukawana–Puncak Upas menawarkan pengalaman perjalanan pegunungan yang lebih panjang dengan suasana hutan dan kemungkinan kabut. Penggunaan Rute serta aktivitas camping hanya ditentukan setelah konsultasi dan pemeriksaan WNB.",
    duration: {
      dry: "5–7 jam",
      rainy: "6–9 jam",
      note: "Estimasi sangat dipengaruhi cuaca, kabut, kondisi jalur, dan susunan kegiatan.",
    },
    landscape: "Hutan pegunungan dan kawasan Puncak Upas",
    trackCharacteristics: [
      "Jalur berbatu",
      "Akar pohon",
      "Tanjakan pegunungan",
      "Lintasan hutan dan kemungkinan kabut",
    ],
    attractions: [
      "Suasana ekspedisi pegunungan",
      "Hutan berkabut",
      "Lanskap kawasan Tangkuban Parahu",
    ],
    activities: [
      "Jelajah off-road",
      "Menikmati lanskap pegunungan",
      "Dokumentasi",
      "Camping apabila menjadi bagian Paket yang telah dikonfirmasi",
    ],
    seasonNote: "Kabut dan hujan dapat memengaruhi jarak pandang, waktu perjalanan, serta keputusan penggunaan Rute.",
    meetingPoint: "Fleksibel berdasarkan Paket dan hasil konfirmasi pemesanan.",
    startArea: "Kawasan Sukawana secara umum",
    finishArea: "Kawasan Puncak Upas secara umum",
    publicSafetyNotes: [
      "Rute hanya digunakan setelah kondisi cuaca dan jalur dinilai memungkinkan.",
      "Susunan kegiatan dapat berubah demi keselamatan peserta.",
      "Aktivitas camping tidak otomatis termasuk dan wajib dikonfirmasi terpisah.",
    ],
    media: {
      alt: "Visual ekspedisi Land Rover klasik menuju kawasan Puncak Upas",
    },
  },
  {
    id: "RT-04",
    order: 4,
    slug: "lingkar-hutan-pinus-cikole",
    name: "Lingkar Hutan Pinus Cikole",
    region: "bandung-utara",
    regionLabel: "Bandung Utara",
    area: "Lembang",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Jelajah Ringan Hutan Pinus Cikole",
    shortDescription: "Perjalanan berbentuk loop di kawasan hutan pinus Cikole dengan ritme lebih ringan untuk perjalanan pertama, keluarga, dan dokumentasi.",
    longDescription: "Lingkar Hutan Pinus Cikole dirancang sebagai pilihan perjalanan dengan ritme lebih ringan tanpa menghilangkan karakter petualangan Land Rover. Kesesuaian untuk keluarga, pemula, atau anak tetap dikonfirmasi pada saat perencanaan.",
    duration: {
      dry: "1,5–2,5 jam",
      rainy: "2–3 jam",
      note: "Estimasi bersifat indikatif dan dapat berubah mengikuti kondisi kawasan.",
    },
    landscape: "Hutan pinus Cikole",
    trackCharacteristics: [
      "Jalur tanah",
      "Batu ringan",
      "Tikungan hutan",
      "Genangan ringan",
    ],
    attractions: [
      "Suasana hutan pinus",
      "Udara pegunungan",
      "Area dokumentasi yang ditentukan kru",
    ],
    activities: [
      "Fun off-road",
      "Perjalanan keluarga atau pemula",
      "Dokumentasi",
      "Piknik atau acara ringan apabila dikonfirmasi dalam Paket",
    ],
    seasonNote: "Hujan dapat membuat permukaan lebih becek dan licin, tetapi susunan perjalanan tetap ditentukan oleh tim WNB.",
    meetingPoint: "Fleksibel di area Cikole atau Lembang berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Cikole secara umum",
    finishArea: "Kawasan Cikole secara umum",
    publicSafetyNotes: [
      "Kesesuaian perjalanan untuk anak dikonfirmasi saat perencanaan.",
      "Peserta tetap wajib mengikuti arahan keselamatan kru.",
      "Durasi dan lintasan dapat disesuaikan dengan kondisi kawasan.",
    ],
    media: {
      alt: "Visual keluarga menikmati Rute Lingkar Hutan Pinus Cikole",
    },
  },
  {
    id: "RT-05",
    order: 5,
    slug: "trek-klasik-jayagiri-cikole",
    name: "Trek Klasik Jayagiri–Cikole",
    region: "bandung-utara",
    regionLabel: "Bandung Utara",
    area: "Lembang",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Jelajah Klasik Jayagiri–Cikole",
    shortDescription: "Jelajah dari kawasan Jayagiri menuju Cikole melalui makadam, perkebunan, jalur hutan, akar, dan genangan dengan karakter petualangan sedang.",
    longDescription: "Trek Klasik Jayagiri–Cikole memadukan suasana kawasan perkebunan, pedesaan, dan hutan. Kondisi aktual lintasan dan waktu perjalanan selalu mengikuti pemeriksaan serta konfirmasi WNB.",
    duration: {
      dry: "2,5–3,5 jam",
      rainy: "3,5–4,5 jam",
      note: "Estimasi bersifat indikatif dan dapat berubah mengikuti kondisi perjalanan.",
    },
    landscape: "Perkebunan, kawasan Jayagiri, dan hutan Cikole",
    trackCharacteristics: [
      "Makadam",
      "Jalur perkebunan",
      "Akar pohon",
      "Genangan dan jalur hutan",
    ],
    attractions: [
      "Suasana kawasan Jayagiri",
      "Perkebunan dan hutan",
      "Perjalanan klasik Bandung Utara",
    ],
    activities: [
      "Jelajah alam",
      "Dokumentasi perjalanan",
      "Menikmati lanskap perkebunan dan hutan",
    ],
    seasonNote: "Hujan dapat membuat akar, tanah, dan genangan lebih licin serta memperpanjang perjalanan.",
    meetingPoint: "Fleksibel di area Lembang atau Cikole berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Jayagiri secara umum",
    finishArea: "Kawasan Cikole secara umum",
    publicSafetyNotes: [
      "Kondisi lintasan diperiksa sebelum perjalanan.",
      "Perjalanan dapat disesuaikan apabila jalur sedang ramai atau tidak memungkinkan.",
      "Peserta wajib mengikuti arahan kru.",
    ],
    media: {
      alt: "Visual Land Rover klasik melintasi Trek Jayagiri–Cikole",
    },
  },
  {
    id: "RT-06",
    order: 6,
    slug: "puncak-gunung-putri-cikole",
    name: "Puncak Gunung Putri–Cikole",
    region: "bandung-utara",
    regionLabel: "Bandung Utara",
    area: "Lembang",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Jelajah Gunung Putri dan Hutan Cikole",
    shortDescription: "Jelajah kawasan Gunung Putri menuju Cikole melalui jalur pegunungan, tanah merah, akar, tanjakan, turunan, dan hutan pinus.",
    longDescription: "Puncak Gunung Putri–Cikole menghadirkan perpaduan suasana pegunungan dan hutan pinus. Angka durasi bersifat indikatif, sedangkan lintasan aktual ditentukan melalui pemeriksaan dan konfirmasi WNB.",
    duration: {
      dry: "3–4 jam",
      rainy: "4–6 jam",
      note: "Estimasi indikatif dan dapat berubah mengikuti cuaca serta kondisi jalur.",
    },
    landscape: "Gunung Putri dan hutan pinus Cikole",
    trackCharacteristics: [
      "Tanah merah",
      "Akar pohon",
      "Tanjakan dan turunan",
      "Jalur hutan pinus",
    ],
    attractions: [
      "Lanskap Gunung Putri",
      "Suasana hutan pinus",
      "Udara pegunungan",
    ],
    activities: [
      "Jelajah off-road",
      "Menikmati lanskap",
      "Dokumentasi pada titik aman",
    ],
    seasonNote: "Kabut, hujan, dan genangan dapat mengubah durasi serta susunan perjalanan.",
    meetingPoint: "Fleksibel di area Lembang atau Cikole berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Gunung Putri secara umum",
    finishArea: "Kawasan Cikole secara umum",
    publicSafetyNotes: [
      "Rute dikonfirmasi berdasarkan kondisi lapangan.",
      "Informasi lokasi rinci diberikan setelah pemesanan dikonfirmasi.",
      "Peserta wajib mengikuti arahan kru.",
    ],
    media: {
      alt: "Visual perjalanan Land Rover klasik dari Gunung Putri menuju Cikole",
    },
  },
  {
    id: "RT-07",
    order: 7,
    slug: "situ-cileunca-hutan-rahong",
    name: "Situ Cileunca–Hutan Rahong",
    region: "bandung-selatan",
    regionLabel: "Bandung Selatan",
    area: "Pangalengan",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Petualangan Situ Cileunca dan Hutan Rahong",
    shortDescription: "Perjalanan Bandung Selatan yang memadukan suasana danau, perkebunan, jalur tanah dan batu, serta kawasan hutan Rahong.",
    longDescription: "Situ Cileunca–Hutan Rahong menawarkan suasana Bandung Selatan melalui perpaduan danau, perkebunan, dan hutan. Detail akses dan susunan perjalanan ditentukan melalui konsultasi serta pemeriksaan WNB.",
    duration: {
      dry: "4–5 jam",
      rainy: "5–7 jam",
      note: "Estimasi indikatif dan dapat berubah mengikuti cuaca serta kondisi kawasan.",
    },
    landscape: "Danau, perkebunan, dan hutan Rahong",
    trackCharacteristics: [
      "Jalur tanah",
      "Batu",
      "Lumpur",
      "Perkebunan dan kawasan hutan",
    ],
    attractions: [
      "Panorama Situ Cileunca",
      "Lanskap perkebunan",
      "Suasana Hutan Rahong",
    ],
    activities: [
      "Jelajah off-road",
      "Dokumentasi danau dan perkebunan",
      "Aktivitas luar ruang sesuai Paket yang dikonfirmasi",
    ],
    seasonNote: "Hujan dapat meningkatkan lumpur dan aliran air sehingga waktu atau susunan perjalanan dapat berubah.",
    meetingPoint: "Fleksibel di Pangalengan atau kawasan Situ Cileunca berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Situ Cileunca secara umum",
    finishArea: "Kawasan Hutan Rahong secara umum",
    publicSafetyNotes: [
      "Akses kawasan dan kondisi perjalanan dikonfirmasi sebelum keberangkatan.",
      "Titik perjalanan rinci tidak ditampilkan secara publik.",
      "Rute dapat disesuaikan atau dialihkan.",
    ],
    media: {
      alt: "Visual perjalanan Land Rover klasik di Situ Cileunca dan Hutan Rahong",
    },
  },
  {
    id: "RT-08",
    order: 8,
    slug: "rancabali-lumpur-eretan",
    name: "Rancabali–Lumpur Eretan",
    region: "bandung-selatan",
    regionLabel: "Bandung Selatan",
    area: "Ciwidey",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Tantangan Lumpur Rancabali",
    shortDescription: "Petualangan perkebunan dan lintasan berlumpur di kawasan Rancabali dengan cerukan, genangan, dan tanjakan tanah.",
    longDescription: "Rancabali–Lumpur Eretan menonjolkan pengalaman lintasan perkebunan dan lumpur. Kondisi jalur dapat berubah secara signifikan setelah hujan sehingga penggunaan Rute selalu mengikuti pemeriksaan WNB.",
    duration: {
      dry: "3–4 jam",
      rainy: "4–6 jam",
      note: "Estimasi indikatif dan sangat dipengaruhi kondisi lumpur serta cuaca.",
    },
    landscape: "Perkebunan Rancabali dan lintasan berlumpur",
    trackCharacteristics: [
      "Tanah lempung",
      "Lumpur",
      "Cerukan dan genangan",
      "Tanjakan tanah",
    ],
    attractions: [
      "Lanskap perkebunan Rancabali",
      "Udara sejuk Ciwidey",
      "Pengalaman lintasan lumpur",
    ],
    activities: [
      "Jelajah off-road",
      "Menikmati tantangan lintasan",
      "Dokumentasi kendaraan pada titik aman",
    ],
    seasonNote: "Hujan dapat memperdalam lumpur dan mengubah waktu serta jalur perjalanan.",
    meetingPoint: "Fleksibel di Ciwidey atau Rancabali berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Rancabali secara umum",
    finishArea: "Kawasan lintasan Lumpur Eretan secara umum",
    publicSafetyNotes: [
      "Kondisi jalur diperiksa sebelum keberangkatan.",
      "Prosedur recovery tidak ditampilkan sebagai informasi publik.",
      "Peserta wajib mengikuti arahan keselamatan kru.",
    ],
    media: {
      alt: "Visual Land Rover klasik melewati lintasan lumpur Rancabali",
    },
  },
  {
    id: "RT-09",
    order: 9,
    slug: "trek-kebun-teh-gambung",
    name: "Trek Kebun Teh Gambung",
    region: "bandung-selatan",
    regionLabel: "Bandung Selatan",
    area: "Ciwidey",
    availabilityStatus: "available-by-confirmation",
    experienceLabel: "Jelajah Sejuk Kebun Teh Gambung",
    shortDescription: "Jelajah kawasan kebun teh Gambung melalui makadam, tanah padat, kerikil, genangan ringan, dan lanskap perkebunan terbuka.",
    longDescription: "Trek Kebun Teh Gambung menghadirkan perjalanan melalui hamparan perkebunan dan lanskap terbuka Bandung Selatan. Titik perjalanan dan akses kawasan ditentukan melalui konfirmasi WNB.",
    duration: {
      dry: "3–4 jam",
      rainy: "4–5 jam",
      note: "Estimasi indikatif dan dapat berubah mengikuti cuaca serta akses kawasan.",
    },
    landscape: "Kebun teh Gambung dan jalur perkebunan",
    trackCharacteristics: [
      "Makadam",
      "Tanah padat",
      "Kerikil",
      "Genangan ringan",
    ],
    attractions: [
      "Hamparan kebun teh Gambung",
      "Lanskap perkebunan terbuka",
      "Udara pegunungan",
    ],
    activities: [
      "Jelajah perkebunan",
      "Dokumentasi",
      "Perjalanan keluarga atau kelompok kecil sesuai konfirmasi",
    ],
    seasonNote: "Hujan dan kabut dapat membuat jalur lebih licin serta memengaruhi jarak pandang.",
    meetingPoint: "Fleksibel di Ciwidey atau Gambung berdasarkan konfirmasi pemesanan.",
    startArea: "Kawasan Kebun Teh Gambung secara umum",
    finishArea: "Kawasan Kebun Teh Gambung secara umum",
    publicSafetyNotes: [
      "Akses dan titik berhenti mengikuti izin serta arahan pengelola kawasan.",
      "Lokasi rinci diberikan setelah pemesanan dikonfirmasi.",
      "Susunan perjalanan dapat berubah mengikuti kondisi lapangan.",
    ],
    media: {
      alt: "Visual Land Rover klasik di kawasan Kebun Teh Gambung",
    },
  },
  {
    id: "RT-10",
    order: 10,
    slug: "rute-khusus-bogor",
    name: "Rute Khusus Bogor",
    region: "rute-khusus",
    regionLabel: "Rute Khusus",
    area: "Bogor",
    availabilityStatus: "special-consultation",
    experienceLabel: "Ekspedisi Khusus Bogor",
    shortDescription: "Rute khusus di kawasan Bogor dengan karakter perbukitan, hutan, tanah merah, bebatuan, akar, dan pengalaman ekspedisi yang disesuaikan.",
    longDescription: "Rute Khusus Bogor ditampilkan sebagai pilihan perjalanan yang disusun melalui konsultasi. Lokasi rinci, jadwal, durasi, bentuk perjalanan, dan ketersediaannya tidak ditetapkan otomatis.",
    duration: {
      dry: "Menyesuaikan hasil konsultasi",
      rainy: "Menyesuaikan kondisi dan keputusan WNB",
      note: "Tidak tersedia sebagai jadwal reguler dan wajib dikonfirmasi terlebih dahulu.",
    },
    landscape: "Perbukitan dan hutan Bogor",
    trackCharacteristics: [
      "Jalur perbukitan",
      "Tanah merah",
      "Bebatuan dan akar",
      "Lintasan hutan",
    ],
    attractions: [
      "Lanskap perbukitan Bogor",
      "Suasana hutan",
      "Pengalaman ekspedisi yang disesuaikan",
    ],
    activities: [
      "Konsultasi perjalanan khusus",
      "Jelajah off-road",
      "Dokumentasi sesuai susunan perjalanan",
    ],
    seasonNote: "Cuaca dan kondisi kawasan menjadi dasar utama penetapan jadwal dan susunan perjalanan.",
    meetingPoint: "Ditentukan setelah konsultasi dan konfirmasi WNB.",
    startArea: "Ditentukan setelah konsultasi",
    finishArea: "Ditentukan setelah konsultasi",
    publicSafetyNotes: [
      "Rute tidak tersedia sebagai pemesanan reguler otomatis.",
      "Lokasi dan jadwal hanya diberikan setelah rencana perjalanan disetujui.",
      "WNB dapat menolak atau menunda perjalanan apabila kondisi belum memungkinkan.",
    ],
    media: {
      alt: "Visual konseptual ekspedisi Land Rover klasik di kawasan Bogor",
    },
  },
] as const;

export function getAllRoutes(): TravelRoute[] {
  return [...TRAVEL_ROUTES].sort((a, b) => a.order - b.order);
}

export function getRoutesByRegion(region: RouteRegion | "semua"): TravelRoute[] {
  const routes = getAllRoutes();
  if (region === "semua") {
    return routes;
  }
  return routes.filter((route) => route.region === region);
}

export function getRouteBySlug(slug?: string): TravelRoute | undefined {
  if (!slug) return undefined;
  return TRAVEL_ROUTES.find((route) => route.slug === slug);
}
